name: Python Tests

# Trigger: Der Workflow wird bei jedem Push und Pull-Request auf den main-Branch ausgeführt
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Der Job läuft auf einem Ubuntu-Runner

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run Unit Tests with Coverage
        run: |
          coverage run -m pytest
          coverage report
